### ISSUE TITLE
Thank you for the beautiful app

### ISSUE THREAD

**Issue by 00itsm00** [dgbkn/torflixapp#1]
Firstly thank you for the beautiful app. 

Secondly no option to delete the files.

Darkmode is not permanent. Every time ll have to turn it on whenever we open the app.

Note: had few files in my account uploaded before i started using this app. I logged into this app and searched for a torrent and added the torrent resulting deleting all of other files.

Please clarify is it it's default behaviour that if the storage is low it automatically clears the files or is it a bug.

Thanks.

**Comment by dgbkn** [comment]
Yes bro its a default behaviour,you can recommend something else also if you wnat
